# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: EA5HVK.VARAHF
PackageVersion: 4.8.9
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: VARA setup (Run as Administrator).exe
Installers:
- Architecture: neutral
  InstallerUrl: https://downloads.winlink.org/VARA%20Products/VARA%20HF%20v4.8.9%20%20setup.zip
  InstallerSha256: F73A4FA2290DAB7399B96A2D2788314FE9839F3CA6FF0C1CF9727D8E4166BD5A
ManifestType: installer
ManifestVersion: 1.10.0
