# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: ireasoning.mibbrowser
PackageVersion: "15.5015"
PackageLocale: en-US
Publisher: iReasoning
PackageName: MIBBrowser
License: MIB Browser License Agreement
ShortDescription: Mib Browser Free Personal Edition - allows viewing MIB files in a GUI and managing SNMP devices
ManifestType: defaultLocale
ManifestVersion: 1.9.0
